In [29]:
import pandas as pd

In [30]:
df = pd.read_csv("wines_enriched_tobevalidatedandfilled.csv",header=1, encoding="utf-8", engine="python", sep=";")
df

,productname,occurrences,Unnamed: 2,Color,Grape,Ph-value,Total acidity,Alcohol in percent,Residual Sugar,Origin country,Origin Region,Price euro,Quality_Level,Style_Descriptors,Aroma_Notes,Food paring matches with,Confidence
0,Bogle Chardonnay,16569,NaN,White,Chardonnay,3.5,5.5,14.5,Dry,USA,California,12.50,Table Wine,"Oaked, balanced","Vanilla, apple, spice",Roast chicken,High
1,Lugana,16403,NaN,White,Turbiana,3.2,6.5,12.5,Dry,Italy,Lugana,13.00,DOC,"Fresh, mineral","Citrus, almond, floral",Seafood,High
2,Maison Centauree Chardonnay,12193,NaN,White,Chardonnay,3.5,5.4,13.0,Dry,France,Languedoc,4.50,IGP,"Fruity, soft","Apple, peach",Salad,High
3,The Chocolate Block,11686,NaN,Red,Syrah blend,3.8,5.1,14.7,3.6 g/L,South Africa,Swartland,33.00,WO,"Full, vibrant","Dark berry, spice",Steak,High
4,Pouilly Fume,11662,NaN,White,Sauvignon Blanc,3.2,6.5,13.0,Dry,France,Loire,16.00,AOC,"Crisp, smoky","Mineral, citrus",Goat cheese,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2156,Marrone - Dolcevita - 2021,361,NaN,Rosé,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High
2157,Peter Lauer - Schonfels11 GG - 2017,360,NaN,White,Riesling,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High
2158,Bodegas Lopez de Heredia Vina Bosconia Tinto R...,360,NaN,Red,"Tempranillo, Garnacha, Mazuelo, Graciano",3.3,6.7 grams of tartaric acid per liter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High
2159,"Margaux, Chateau Brane-Cantenac",360,NaN,Red,Bordeaux blend (typically including Cabernet S...,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High
2160,Chateau de Saint Cosme Saint-Joseph,360,NaN,Red,100% Syrah (local Sérine variety),3.88,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High

In [31]:
# First, let's see what's in the problematic line
with open("wines_enriched_tobevalidatedandfilled.csv", 'r') as f:
    lines = f.readlines()
    print("First 5 lines:")
    for i, line in enumerate(lines[:5], 1):
        print(f"Line {i}: {line.strip()}")

First 5 lines:
Line 1: wines_enriched
Line 2: productname;occurrences;;Color;Grape;Ph-value;Total acidity;Alcohol in percent;Residual Sugar;Origin country;Origin Region;Price euro;Quality_Level;Style_Descriptors;Aroma_Notes ;Food paring matches with;Confidence
Line 3: Bogle Chardonnay;16569;;White;Chardonnay;3.5;5.5;14.5;Dry;USA;California;12.50;Table Wine;Oaked, balanced;Vanilla, apple, spice;Roast chicken;High
Line 4: Lugana;16403;;White;Turbiana;3.2;6.5;12.5;Dry;Italy;Lugana;13.00;DOC;Fresh, mineral;Citrus, almond, floral;Seafood;High
Line 5: Maison Centauree Chardonnay;12193;;White;Chardonnay;3.5;5.4;13.0;Dry;France;Languedoc;4.50;IGP;Fruity, soft;Apple, peach;Salad;High

In [32]:
df.head()

,productname,occurrences,Unnamed: 2,Color,Grape,Ph-value,Total acidity,Alcohol in percent,Residual Sugar,Origin country,Origin Region,Price euro,Quality_Level,Style_Descriptors,Aroma_Notes,Food paring matches with,Confidence
0,Bogle Chardonnay,16569,NaN,White,Chardonnay,3.5,5.5,14.5,Dry,USA,California,12.50,Table Wine,"Oaked, balanced","Vanilla, apple, spice",Roast chicken,High
1,Lugana,16403,NaN,White,Turbiana,3.2,6.5,12.5,Dry,Italy,Lugana,13.00,DOC,"Fresh, mineral","Citrus, almond, floral",Seafood,High
2,Maison Centauree Chardonnay,12193,NaN,White,Chardonnay,3.5,5.4,13.0,Dry,France,Languedoc,4.50,IGP,"Fruity, soft","Apple, peach",Salad,High
3,The Chocolate Block,11686,NaN,Red,Syrah blend,3.8,5.1,14.7,3.6 g/L,South Africa,Swartland,33.00,WO,"Full, vibrant","Dark berry, spice",Steak,High
4,Pouilly Fume,11662,NaN,White,Sauvignon Blanc,3.2,6.5,13.0,Dry,France,Loire,16.00,AOC,"Crisp, smoky","Mineral, citrus",Goat cheese,High

In [33]:
#df=df.drop(columns=['NaN'])
df.columns

Index(['productname', 'occurrences', 'Unnamed: 2', 'Color', 'Grape',
       'Ph-value', 'Total acidity', 'Alcohol in percent', 'Residual Sugar',
       'Origin country', 'Origin Region', 'Price euro', 'Quality_Level',
       'Style_Descriptors', 'Aroma_Notes ', 'Food paring matches with',
       'Confidence'],
      dtype='object')

In [34]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

In [35]:
df.columns

Index(['productname', 'occurrences', 'Color', 'Grape', 'Ph-value',
       'Total acidity', 'Alcohol in percent', 'Residual Sugar',
       'Origin country', 'Origin Region', 'Price euro', 'Quality_Level',
       'Style_Descriptors', 'Aroma_Notes ', 'Food paring matches with',
       'Confidence'],
      dtype='object')

In [36]:
df

,productname,occurrences,Color,Grape,Ph-value,Total acidity,Alcohol in percent,Residual Sugar,Origin country,Origin Region,Price euro,Quality_Level,Style_Descriptors,Aroma_Notes,Food paring matches with,Confidence
0,Bogle Chardonnay,16569,White,Chardonnay,3.5,5.5,14.5,Dry,USA,California,12.50,Table Wine,"Oaked, balanced","Vanilla, apple, spice",Roast chicken,High
1,Lugana,16403,White,Turbiana,3.2,6.5,12.5,Dry,Italy,Lugana,13.00,DOC,"Fresh, mineral","Citrus, almond, floral",Seafood,High
2,Maison Centauree Chardonnay,12193,White,Chardonnay,3.5,5.4,13.0,Dry,France,Languedoc,4.50,IGP,"Fruity, soft","Apple, peach",Salad,High
3,The Chocolate Block,11686,Red,Syrah blend,3.8,5.1,14.7,3.6 g/L,South Africa,Swartland,33.00,WO,"Full, vibrant","Dark berry, spice",Steak,High
4,Pouilly Fume,11662,White,Sauvignon Blanc,3.2,6.5,13.0,Dry,France,Loire,16.00,AOC,"Crisp, smoky","Mineral, citrus",Goat cheese,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2156,Marrone - Dolcevita - 2021,361,Rosé,Not Available,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High
2157,Peter Lauer - Schonfels11 GG - 2017,360,White,Riesling,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High
2158,Bodegas Lopez de Heredia Vina Bosconia Tinto R...,360,Red,"Tempranillo, Garnacha, Mazuelo, Graciano",3.3,6.7 grams of tartaric acid per liter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High
2159,"Margaux, Chateau Brane-Cantenac",360,Red,Bordeaux blend (typically including Cabernet S...,Not Available,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High
2160,Chateau de Saint Cosme Saint-Joseph,360,Red,100% Syrah (local Sérine variety),3.88,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,High

In [43]:
df.reset_index(inplace=True)

In [45]:
df.columns

Index(['index', 'productname', 'occurrences', 'Color', 'Grape', 'Ph-value',
       'Total acidity', 'Alcohol in percent', 'Residual Sugar',
       'Origin country', 'Origin Region', 'Price euro', 'Quality_Level',
       'Style_Descriptors', 'Aroma_Notes ', 'Food paring matches with',
       'Confidence'],
      dtype='object')

In [46]:
df.columns = df.columns.str.strip()

In [48]:
df = df.drop(columns=['index'], errors='ignore')

In [37]:
df.duplicated().sum()

0

In [49]:
df

,productname,occurrences,Color,Grape,Ph-value,Total acidity,Alcohol in percent,Residual Sugar,Origin country,Origin Region,Price euro,Quality_Level,Style_Descriptors,Aroma_Notes,Food paring matches with,Confidence
0,Bogle Chardonnay,16569,White,Chardonnay,3.5,5.5,14.5,Dry,USA,California,12.50,Table Wine,"Oaked, balanced","Vanilla, apple, spice",Roast chicken,High
1,Lugana,16403,White,Turbiana,3.2,6.5,12.5,Dry,Italy,Lugana,13.00,DOC,"Fresh, mineral","Citrus, almond, floral",Seafood,High
2,Maison Centauree Chardonnay,12193,White,Chardonnay,3.5,5.4,13.0,Dry,France,Languedoc,4.50,IGP,"Fruity, soft","Apple, peach",Salad,High
3,The Chocolate Block,11686,Red,Syrah blend,3.8,5.1,14.7,3.6 g/L,South Africa,Swartland,33.00,WO,"Full, vibrant","Dark berry, spice",Steak,High
4,Pouilly Fume,11662,White,Sauvignon Blanc,3.2,6.5,13.0,Dry,France,Loire,16.00,AOC,"Crisp, smoky","Mineral, citrus",Goat cheese,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Enracines Macon Chardonnay,3947,White,Chardonnay,N.N.,N.N.,13.0,N.N.,France,Burgundy (Mâcon),N.N.,AOP,"Fresh, floral","Apple, citrus","Grilled chicken, seafood",High
85,Chateauneuf du Pape Rouge,3927,Red,Blend (Grenache-dominant; up to 13 permitted v...,N.N.,N.N.,N.N.,N.N.,France,Southern Rhône (Châteauneuf-du-Pape),N.N.,AOC,"Structured, spicy","Red berries, garrigue","Lamb, stews",High
86,Chablis 1er Cru,3907,White,Chardonnay,N.N.,N.N.,N.N.,N.N.,France,Burgundy (Chablis 1er Cru),N.N.,AOC Premier Cru,"Mineral, elegant","Citrus, flint","Seafood, poultry",High
87,053 - HIBERNAL,3887,White,Hibernal,N.N.,N.N.,N.N.,N.N.,Czech Republic,N.N.,N.N.,N.N.,"Crisp, aromatic (typical)","Currant, citrus (typical)","Fish, seafood, salads",High
88,Francis Coppola,3849,Rosé,Pinot Noir,N.N.,N.N.,N.N.,N.N.,USA,California,N.N.,N.N.,"Dry, fruity","Strawberry, citrus","Salads, light dishes",High

In [50]:
df.isnull().sum()

productname                 0
occurrences                 0
Color                       0
Grape                       0
Ph-value                    0
Total acidity               0
Alcohol in percent          0
Residual Sugar              0
Origin country              0
Origin Region               0
Price euro                  0
Quality_Level               0
Style_Descriptors           0
Aroma_Notes                 0
Food paring matches with    0
Confidence                  0
dtype: int64

In [51]:
null_pct = df.isnull().mean() * 100
null_pct

productname                 0.0
occurrences                 0.0
Color                       0.0
Grape                       0.0
Ph-value                    0.0
Total acidity               0.0
Alcohol in percent          0.0
Residual Sugar              0.0
Origin country              0.0
Origin Region               0.0
Price euro                  0.0
Quality_Level               0.0
Style_Descriptors           0.0
Aroma_Notes                 0.0
Food paring matches with    0.0
Confidence                  0.0
dtype: float64

In [52]:
df = df.drop_duplicates()
df.shape

(89, 16)

In [41]:
df.dropna(inplace=True)
df.shape

(89, 16)

In [54]:
df.to_csv("wine_enriched_clean.csv", index=False)